# Pytest Configuration for Admission System

[tool:pytest]
# Test discovery patterns
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Test paths
testpaths = tests

# Output options
addopts = 
    -v
    --tb=short
    --strict-markers
    --disable-warnings
    --cov=backend
    --cov-report=html
    --cov-report=term-missing:skip-covered

# Markers for organizing tests
markers =
    unit: Unit tests for individual components
    integration: Integration tests for multiple components
    auth: Authentication and authorization tests
    models: Database model tests
    routes: Route/endpoint tests
    slow: Tests that take a long time to run

# Coverage options
[coverage:run]
source = backend
omit = 
    */tests/*
    */venv/*
    */__pycache__/*
    */migrations/*

[coverage:report]
precision = 2
show_missing = True
skip_covered = False
